### ISSUE TITLE
Bug: Unable to use the latest release of the GitHub action

### ISSUE THREAD

**Issue by bramdehart** [Azure/k8s-deploy#300]
### What happened?

New version 1.10.0 was released 3 days ago: https://github.com/Azure/k8s-deploy/releases/tag/4.10.0
However, in the GitHub action release page, the new version is not listed:
![image](https://github.com/Azure/k8s-deploy/assets/110542946/1e0a04df-24b5-4264-825d-8dae5f4b2c79)
Yet, the latest tag is visible on when the 'Use latest version' option is selected:
![image](https://github.com/Azure/k8s-deploy/assets/110542946/da0604ad-f02c-49e2-badd-f2f9cbb2f186)

![image](https://github.com/Azure/k8s-deploy/assets/110542946/c6ad58e2-aa4a-4e1d-b698-5657a189ce85)

I am unable to resolve the latest version:
![image](https://github.com/Azure/k8s-deploy/assets/110542946/4e3029d2-b0a5-435e-a410-cc1c2878563f)
Also, unable to retrieve lates release by the following links:
https://github.com/marketplace/actions/deploy-to-kubernetes-cluster?version=v10.0
https://github.com/marketplace/actions/deploy-to-kubernetes-cluster?version=10.0
https://github.com/marketplace/actions/deploy-to-kubernetes-cluster?version=latest

### Version

- [X] I am using the latest version

### Runner

self-hosted

### Relevant log output

![image](https://github.com/Azure/k8s-deploy/assets/110542946/a3bd93ff-dcd8-4aa9-b8d0-0febe92c6eb0)

Does is have to do with the new release workflow?: https://github.com/Azure/k8s-deploy/pull/297

**Comment by davidgamero** [comment]
this appears to be related to an issue with the updated release workflow missing the lib directory, which should be fixed by https://github.com/Azure/action-release-workflows/pull/1

patching now with https://github.com/Azure/k8s-deploy/pull/301

**Comment by davidgamero** [comment]
release v4.10.0 has been regenerated, and I can see the /lib directory with run.ts now, so that should get us back up and running. @bramdehart please let us know when you have a chance to try it out

**Comment by bramdehart** [comment]
@davidgamero  I will try but am mostly sure it still wouldn't work. The version is still not listed in the github action marketplace page. See for exameple

![image](https://github.com/Azure/k8s-deploy/assets/110542946/2d353b37-e895-4400-819e-ec8e1b1fbb36)
Were the latest version is also listed as the tag

This is not the case with this action
![image](https://github.com/Azure/k8s-deploy/assets/110542946/abd6d14d-7cf1-48c8-95c0-0d36763b7fb0)


Also you can spot the formatting difference in tagging, with and without 'v' since release refactor.

**Comment by bramdehart** [comment]
@davidgamero I can confirm that is now works. Still weird that is not listed as seperate tag on the Github Action page on marketplace. Issue resolved :)

**Comment by davidgamero** [comment]
I see what you mean with the missing tag on the action page. Ill take a look, but Im glad it's working for you now!
